### ISSUE TITLE
Cuffnorm

### ISSUE THREAD

**Issue by johanneskoester** [cole-trapnell-lab/cufflinks#35] opened 2015-07-14 09:12 UTC
With ~130 samples, and cxb files of about 20GB in sum, cuffnorm 2.2.1 seems to use more than 80GB of memory. Is that expected, and can I do anything to reduce the memory consumption?

**Comment by ctrapnell** [comment] 2015-07-29 20:12
That's larger than I've ever seen the footprint get. Can you reproduce this with the current revision of the develop branch?

**Comment by johanneskoester** [comment] 2015-08-07 13:49
Hi,
unfortunately, I had to try a different way (using cufflinks on the merged transcripts), because I could not wait. Since I don't have the cxb files any more, retrying with the dev branch is not an option right now because of the computational effort. For me, the issue sounds like a memory leak, because the used memory was bigger than the input cxbs. Maybe you should just run valgrind on cuffnorm?

Sorry that I cannot help you directly with testing.

**Comment by ctrapnell** [comment] 2015-08-12 22:44
I asked because the current master include some major memory improvements that impact cuffnorm and cuffdiff that haven't yet been released. We regularly run valgrind to certify that all Cufflinks utilities are free of leaks (at least the kind that valgrind can detect). Both 2.2.1 and the current master are, to my knowledge, free of leaks.  It's likely that you are just running afoul of the problems that led me to streamline memory usage in cuffnorm since 2.2.1. I'm going to close this one for now, but feel free to re-open if you do try and re-run using a more recent release.

**Closed by ctrapnell** 2015-08-12 22:44 UTC

**Comment by johanneskoester** [comment] 2015-08-12 23:30
Thanks for the explanation! Looking forward to the new release, then ;-).

**Comment by paologuarnieri** [comment] 2016-03-04 15:26
Hi Cole,

I am experiencing the same problem: 300 samples, memory goes up to 60GB then, then at some point it gets killed.
do you have any advice?
Thanks,

Paolo
